{
 "title": "DCP - Mesh Controller",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message delay (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "timestamp(mc_last_message_timestamp) - mc_last_message_timestamp / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mc_network_processing_error_total",
     "legendFormat": "__auto"
    },
    { "expr": "mc_kube_processing_error_total", "legendFormat": "__auto" },
    { "expr": "mc_kube_forcesync_error_total", "legendFormat": "__auto" },
    { "expr": "mc_tick_processing_error_total", "legendFormat": "__auto" },
    { "expr": "mc_kubeapply_conflicts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Applied Increase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(mc_applied_event_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(mc_applied_snapshot_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(mc_applied_event_total[1m])) by (name, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mc_applied_shapshot_total[1m])) by (name, namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "expr": "mc_resources_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "mc_active_peers_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Membership Changes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "increase(mc_membership_change_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Message Received (per zone)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(mc_network_message_received_total[1m])) by (src_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Messages broadcasted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(mc_network_message_broadcasted_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Received SeqNr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "mc_operation_received_seqnr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Operations Applied SeqNr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    { "expr": "mc_operation_applied_seqnr", "legendFormat": "__auto" }
   ]
  }
 ]
}