// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -Af -
// kopium version: 0.21.2

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

/// AnyApplicationSpec defines the desired state of AnyApplication.
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
#[kube(
    group = "dcp.hiro.io",
    version = "v1",
    kind = "AnyApplication",
    plural = "anyapplications"
)]
#[kube(namespaced)]
#[kube(status = "AnyApplicationStatus")]
pub struct AnyApplicationSpec {
    /// Foo is an example field of AnyApplication. Edit anyapplication_types.go to remove/update
    pub application: AnyApplicationApplication,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "placement-strategy"
    )]
    pub placement_strategy: Option<AnyApplicationPlacementStrategy>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "recover-strategy"
    )]
    pub recover_strategy: Option<AnyApplicationRecoverStrategy>,
    pub zones: i64,
}

/// Foo is an example field of AnyApplication. Edit anyapplication_types.go to remove/update
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub struct AnyApplicationApplication {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub helm: Option<AnyApplicationApplicationHelm>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "resourceSelector"
    )]
    pub resource_selector: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub struct AnyApplicationApplicationHelm {
    pub chart: String,
    pub namespace: String,
    pub repository: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<String>,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub struct AnyApplicationPlacementStrategy {
    pub strategy: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub struct AnyApplicationRecoverStrategy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "max-retries"
    )]
    pub max_retries: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tolerance: Option<i64>,
}

/// AnyApplicationStatus defines the observed state of AnyApplication.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct AnyApplicationStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<AnyApplicationStatusConditions>>,
    pub owner: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placements: Option<Vec<AnyApplicationStatusPlacements>>,
    pub state: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct AnyApplicationStatusConditions {
    #[serde(rename = "lastTransitionTime")]
    pub last_transition_time: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub status: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "zoneId")]
    pub zone_id: String,
    #[serde(rename = "zoneVersion")]
    pub zone_version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct AnyApplicationStatusPlacements {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "node-affinity"
    )]
    pub node_affinity: Option<Vec<String>>,
    pub zone: String,
}
